version: '2.1'
orbs:
  node: circleci/node@4.3
jobs:
  build:
    working_directory: ~/project/nodejs
    docker:
        - image: cimg/node:16.1.0
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Start Server
          command: yarn run start
      - run:
          name: Await
          command: dockerize -wait http://localhost:3000 -timeout 1m
      - run:
          command: yarn run test
          name: Run YARN tests
workflows:
  test_my_app:
    jobs:
      - build