# Generated by Django 3.2 on 2021-04-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civ', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bithday', models.DateField()),
                ('mail', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('civ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_cv.civility')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('describe', models.CharField(max_length=1024)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_cv.skillcat')),
            ],
        ),
    ]
